package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"duit-pasutri-be/internal/dto"
)

// AccountCreate is the resolver for the accountCreate field.
func (r *mutationResolver) AccountCreate(ctx context.Context, input dto.AccountUpsert) (*dto.AccountDTO, error) {
	return r.AccountService.Create(ctx, &input)
}

// AccountUpdate is the resolver for the accountUpdate field.
func (r *mutationResolver) AccountUpdate(ctx context.Context, input dto.AccountUpsert) (*dto.AccountDTO, error) {
	return r.AccountService.Update(ctx, &input)
}

// AccountAddUser is the resolver for the accountAddUser field.
func (r *mutationResolver) AccountAddUser(ctx context.Context, input dto.AccountUser) (*dto.AccountDTO, error) {
	return r.AccountService.AddUser(ctx, &input)
}

// AccountDeleteUser is the resolver for the accountDeleteUser field.
func (r *mutationResolver) AccountDeleteUser(ctx context.Context, input dto.AccountUser) (*dto.AccountDTO, error) {
	return r.AccountService.DeleteUser(ctx, &input)
}

// MyAccounts is the resolver for the myAccounts field.
func (r *queryResolver) MyAccounts(ctx context.Context) ([]*dto.AccountDTO, error) {
	return r.AccountService.GetMyAccounts(ctx)
}

// MyAccountsPage is the resolver for the myAccountsPage field.
func (r *queryResolver) MyAccountsPage(ctx context.Context, input dto.PaginationInput) (*dto.PaginatedAccount, error) {
	return r.AccountService.GetMyAccountsPaginated(ctx, &input)
}

// AccountByID is the resolver for the accountById field.
func (r *queryResolver) AccountByID(ctx context.Context, id string) (*dto.AccountDTO, error) {
	return r.AccountService.GetAccountById(ctx, id)
}
