package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"duit-pasutri-be/internal/dto"
)

// CategoryCreate is the resolver for the categoryCreate field.
func (r *mutationResolver) CategoryCreate(ctx context.Context, input dto.CategoryUpsert) (*dto.CategoryDTO, error) {
	return r.CategoryService.Create(ctx, &input)
}

// CategoryUpdate is the resolver for the categoryUpdate field.
func (r *mutationResolver) CategoryUpdate(ctx context.Context, input dto.CategoryUpsert) (*dto.CategoryDTO, error) {
	return r.CategoryService.Update(ctx, &input)
}

// CategoryDelete is the resolver for the categoryDelete field.
func (r *mutationResolver) CategoryDelete(ctx context.Context, id string) (*dto.CategoryDTO, error) {
	return r.CategoryService.Delete(ctx, id)
}

// CategoriesPage is the resolver for the categoriesPage field.
func (r *queryResolver) CategoriesPage(ctx context.Context, input dto.PaginationInput) (*dto.PaginatedCategory, error) {
	return r.CategoryService.GetAllPaginated(ctx, &input)
}
