package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"duit-pasutri-be/internal/dto"
)

// TransactionCreate is the resolver for the transactionCreate field.
func (r *mutationResolver) TransactionCreate(ctx context.Context, input dto.TransactionUpsert) (*dto.TransactionDTO, error) {
	return r.TransactionService.Create(ctx, &input)
}

// TransactionUpdate is the resolver for the transactionUpdate field.
func (r *mutationResolver) TransactionUpdate(ctx context.Context, input dto.TransactionUpsert) (*dto.TransactionDTO, error) {
	return r.TransactionService.Update(ctx, &input)
}

// TransactionDelete is the resolver for the transactionDelete field.
func (r *mutationResolver) TransactionDelete(ctx context.Context, id string) (*dto.TransactionDTO, error) {
	return r.TransactionService.Delete(ctx, id)
}

// MyTransactionsPage is the resolver for the myTransactionsPage field.
func (r *queryResolver) MyTransactionsPage(ctx context.Context, input dto.PaginationInput) (*dto.PaginatedTransaction, error) {
	return r.TransactionService.GetMyTransactions(ctx, &input)
}
