package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"duit-pasutri-be/internal/dto"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input dto.Register) (*dto.UserDTO, error) {
	return r.UserService.Register(ctx, &input)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input dto.Login) (*dto.LoginResponse, error) {
	return r.UserService.Login(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input dto.UserUpdate) (*dto.UserDTO, error) {
	return r.UserService.Update(ctx, &input)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*dto.UserDTO, error) {
	return r.UserService.GetAll(ctx)
}

// UsersPage is the resolver for the usersPage field.
func (r *queryResolver) UsersPage(ctx context.Context, input dto.PaginationInput) (*dto.PaginatedUser, error) {
	return r.UserService.GetAllPaginated(ctx, &input)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*dto.UserDTO, error) {
	return r.UserService.GetByID(ctx, id)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*dto.UserDTO, error) {
	return r.UserService.Me(ctx)
}
